name: Convert Notebooks and README to PDF

on:
  push:
    branches:
      - main  # Runs on push to main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade nbconvert

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install LaTeX (required for PDF conversion)
        run: |
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic

      - name: Convert Jupyter notebooks to PDF
        run: |
          jupyter nbconvert --to pdf Second_Project.ipynb --log-level=ERROR || echo "Failed to convert Second_Project.ipynb"
          jupyter nbconvert --to pdf Third_Project.ipynb --log-level=ERROR || echo "Failed to convert Third_Project.ipynb"

      - name: Convert README.md to PDF
        run: |
          pandoc README.md -o README.pdf --pdf-engine=xelatex --strip-yaml-front-matter || echo "Failed to convert README.md"

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-files
          path: |
            Second_Project.pdf
            Third_Project.pdf
            README.pdf
