name: Convert Files to PDF
on:
  push:
    branches:
      - main
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install LaTeX, Pandoc, and nbconvert
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra pandoc
          pip install nbconvert

      # Convert Markdown to PDF
      - name: Convert README.md to PDF
        run: |
          pandoc README.md -o README.pdf --pdf-engine=xelatex

      # Convert Jupyter Notebooks to PDF
      - name: Convert Third_Project.ipynb to PDF
        run: |
          jupyter nbconvert --to pdf Third_Project.ipynb

      - name: Convert Second_Project.ipynb to PDF
        run: |
          jupyter nbconvert --to pdf Second_Project.ipynb

      # Upload PDF artifacts
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-files
          path: |
            README.pdf
            Third_Project.pdf
            Second_Project.pdf
