name: Convert Markdown to PDF
on:
  push:
    branches:
      - main
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert Markdown to PDF
        uses: docker://pandoc/latex:latest
        with:
          args: README.md -o output.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: output.pdf
          path: output.pdf
