name: Convert Markdown to PDF
on:
  push:
    branches:
      - main
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX (texlive)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Install Pandoc
        run: |
          sudo apt-get install -y pandoc

      - name: Convert Markdown to PDF
        run: |
          pandoc README.md -o output.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: output.pdf
          path: output.pdf
